services:
  # site
  service--site:
    container_name: ${APP_NAME}__${SITE__SERVICE}
    build: 
      context: ./${SITE__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    env_file:
      - .env-${APP_ENV}
    command: ${SITE__COMAND}
    stdin_open: true
    tty: true
    volumes:
      - ./${SITE__SERVICE}:${APP_DIR}
      # node_modules
      - ./${SITE__SERVICE}/node_modules:${APP_DIR}/node_modules/
    depends_on:
      - ${DB_TEMPORARY__SERVICE}
    restart: ${CONTAINER_RESTART_MODE}

  # admin
  service--admin:
    container_name: ${APP_NAME}__${ADMIN__SERVICE}
    build: 
      context: ./${ADMIN__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    env_file:
      - .env-${APP_ENV}
    command: ${ADMIN__COMAND}
    stdin_open: true
    tty: true
    volumes: 
      - ./${ADMIN__SERVICE}:${APP_DIR}
      # node_modules
      - ./${ADMIN__SERVICE}/node_modules:${APP_DIR}/node_modules/
    depends_on:
      - ${API__SERVICE}
    restart: ${CONTAINER_RESTART_MODE}

  #api
  service--api:
    container_name: ${APP_NAME}__${API__SERVICE}
    build: 
      context: ./${API__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    command: ${API__COMAND}
    env_file:
      - .env-${APP_ENV}
      - .env-custom
    stdin_open: true
    tty: true
    volumes:
      - ./${API__SERVICE}:${APP_DIR}
      - ./${API__SERVICE}/node_modules:${APP_DIR}/node_modules/
      # For parse function $t()
      - ./${ADMIN__SERVICE}/src:${APP_DIR}/services/${ADMIN__SERVICE}
      - ./${SITE__SERVICE}:${APP_DIR}/services/${SITE__SERVICE}
      # db main
      - ./${DB_MAIN__SERVICE}:${APP_DIR}/services/${DB_MAIN__SERVICE}
      # proxy
      - ./${PROXY__SERVICE}:${APP_DIR}/services/${PROXY__SERVICE}
      - ${FILES__STORAGE_NAME}:${APP_DIR}/${FILES__STORAGE_PERMANENT}
    depends_on:
      - ${DB_MAIN__SERVICE}
      - ${DB_TEMPORARY__SERVICE}
    restart: ${CONTAINER_RESTART_MODE}

  # db - posgres
  service--db-main:
    container_name: ${APP_NAME}__${DB_MAIN__SERVICE}
    build: 
      context: ./${DB_MAIN__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    environment:
      POSTGRES_DB: ${DB_MAIN__NAME_DB}
      POSTGRES_PASSWORD: ${DB_MAIN__PASSWORD_DB}
      APP_DIR: ${APP_DIR}
      DB_MAIN__NAME_DB: ${DB_MAIN__NAME_DB}
      DB_MAIN__USER_DB: ${DB_MAIN__USER_DB}
      DB_MAIN__PASSWORD_DB: ${DB_MAIN__PASSWORD_DB}
      DB_MAIN__PORT_INTERNAL: ${DB_MAIN__PORT_INTERNAL}
      DB_MAIN__SERVICE: ${DB_MAIN__SERVICE}
      DB_MAIN__BACKUP_PATHS: ${DB_MAIN__BACKUP_PATHS}
      DB_MAIN__BACKUP_REPORT_PATH: ${DB_MAIN__BACKUP_REPORT_PATH}
      DB_MAIN__BACKUP_MESSAGING_FILE: ${DB_MAIN__BACKUP_MESSAGING_FILE}
      API__SERVICE: ${API__SERVICE}
    ports:
      - ${DB_MAIN__PORT_EXTERNAL}:${DB_MAIN__PORT_INTERNAL}
    stdin_open: true
    tty: true
    volumes:
      # "docker-entrypoint-initdb.d" - creates a table in the database and performs some actions 1 time during initialization (see container documentation)
      - ./${DB_MAIN__SERVICE}/init:/docker-entrypoint-initdb.d:ro
       # Creates a backup
      - ./${DB_MAIN__SERVICE}/server.js:${APP_DIR}/server.js:ro
      - ./${DB_MAIN__SERVICE}/${DB_MAIN__BACKUP_DIR}:${APP_DIR}/${DB_MAIN__BACKUP_DIR}
    restart: ${CONTAINER_RESTART_MODE}

  # db - redis
  service--db-temporary:
    container_name: ${APP_NAME}__${DB_TEMPORARY__SERVICE}
    build: 
      context: ./${DB_TEMPORARY__SERVICE}
    ports:
      - ${DB_TEMPORARY__PORT_EXTERNAL}:${DB_TEMPORARY__PORT_INTERNAL}
    restart: ${CONTAINER_RESTART_MODE}

  # proxy - nginx
  service--proxy:
    container_name: ${APP_NAME}__${PROXY__SERVICE}
    build:
      context: ./${PROXY__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    env_file:
      - .env-${APP_ENV}
      - .env-custom
    ports:
      - ${PROXY__PORT_443}:${PROXY__PORT_443}
      - ${PROXY__PORT_80}:${PROXY__PORT_80}
    volumes:
      # "default.conf.template" - is to be able to pass environment variables to config (see container documentation)
      - ./${PROXY__SERVICE}:${APP_DIR}
      - ${FILES__STORAGE_NAME}:${APP_DIR}/${FILES__STORAGE_PERMANENT}:ro
      - ./${PROXY__SERVICE}/config:${PROXY__CONFIG_DIR}
    depends_on:
      - ${ADMIN__SERVICE}
      - ${SITE__SERVICE}
      - ${API__SERVICE}
      - ${FILES__SERVICE}
    restart: ${CONTAINER_RESTART_MODE}

  # files
  # When initializing a project, the service adds files from a folder named "service--files" (the folder is located on the host) to a volume named "${FILES__STORAGE_NAME}".
  # Note: Files from the "service--files" folder are only added to the "${FILES__STORAGE_NAME}" volume during initialization; this is done for security reasons.
  service--files:
    env_file:
      - .env-${APP_ENV}
      - .env-custom
    container_name: ${APP_NAME}__${FILES__SERVICE}
    build: 
      context: ./${FILES__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    restart: ${CONTAINER_RESTART_MODE}
    volumes:
      - ${FILES__STORAGE_NAME}:${APP_DIR}/${FILES__STORAGE_PERMANENT}
      # - ./${FILES__SERVICE}:${APP_DIR}/${FILES__STORAGE_PERMANENT}

volumes:
  storage--files:
    name: ${APP_NAME}__${FILES__STORAGE_NAME}