services:
  # site
  service--site:
    container_name: ${PROJECT_NAME}__${SITE__SERVICE}
    build: 
      context: ./${SITE__SERVICE}
      args:
        - WORKDIR_BASE=${WORKDIR_BASE}
    command: npm run build 
    volumes:
      - ./${SITE__SERVICE}:${WORKDIR_BASE}
      # node_modules
      - ./${SITE__SERVICE}/node_modules:${WORKDIR_BASE}/node_modules/

  # admin
  service--admin:
    container_name: ${PROJECT_NAME}__${ADMIN__SERVICE}
    build: 
      context: ./${ADMIN__SERVICE}
      args:
        - WORKDIR_BASE=${WORKDIR_BASE}
    command: npm run build
    volumes: 
      - ./${ADMIN__SERVICE}:${WORKDIR_BASE}
      # node_modules
      - ./${ADMIN__SERVICE}/node_modules:${WORKDIR_BASE}/node_modules/