services:
  # site
  service--site:
    container_name: ${APP_NAME}__${SITE__SERVICE}
    build: 
      context: ./${SITE__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    command: npm run build 
    volumes:
      - ./${SITE__SERVICE}:${APP_DIR}
      # node_modules
      - ./${SITE__SERVICE}/node_modules:${APP_DIR}/node_modules/

  # admin
  service--admin:
    container_name: ${APP_NAME}__${ADMIN__SERVICE}
    build: 
      context: ./${ADMIN__SERVICE}
      args:
        - APP_DIR=${APP_DIR}
    command: npm run build
    volumes: 
      - ./${ADMIN__SERVICE}:${APP_DIR}
      # node_modules
      - ./${ADMIN__SERVICE}/node_modules:${APP_DIR}/node_modules/