version: "3.9"

services:
  # site
  service--site:
    container_name: ${PROJECT_NAME}__${SITE__SERVICE}
    build: 
      context: ./${SITE__SERVICE}
      args:
        - WORKDIR_BASE=${WORKDIR_BASE}
        - SERVICE=${SITE__SERVICE}
    command: npm run build 

  # admin
  service--admin:
    container_name: ${PROJECT_NAME}__${ADMIN__SERVICE}
    build: 
      context: ./${ADMIN__SERVICE}
      args:
        - WORKDIR_BASE=${WORKDIR_BASE}
        - SERVICE=${ADMIN__SERVICE}
    command: npm run build